<?xml version='1.0'?>

<robot name="atom" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="robot_name" value="atom" />
	<!-- <xacro:property name="robot_chassis_mass" value="15"/> -->
	<xacro:property name="robot_chassis_mass" value="15" />
	<xacro:property name="robot_chassis_length" value="0.2" />
	<xacro:property name="robot_chassis_radius" value="0.25" />
	<xacro:property name="robot_caster_wheel_radius" value="0.05" />
	<xacro:property name="robot_caster_wheel_radius_collision" value="0.0499" />

	<xacro:property name="robot_wheel_mass" value="3" />
	<!-- <xacro:property name="robot_wheel_length" value="0.05"/> -->
	<xacro:property name="robot_wheel_length" value="0.081497" />
	<!-- <xacro:property name="robot_wheel_radius" value="0.08"/> -->
	<xacro:property name="robot_wheel_radius" value="0.082295" />

	<!-- ========================================================================================== -->
	<!-- Scout Mini Version -->
	<xacro:property name="wheelbase" value="0.463951" />
	<xacro:property name="track" value="0.416503" />
	<xacro:property name="wheel_vertical_offset" value="-0.100998" />

	<!-- <xacro:property name="track" value="0.3426" />
    <xacro:property name="wheelbase" value="0.3181"/>
    <xacro:property name="wheel_vertical_offset" value="-0.160000047342231" /> -->

	<!-- <xacro:property name="wheelbase" value="0.3132556"/>
	<xacro:property name="track" value="0.4563536" />
	<xacro:property name="wheel_vertical_offset" value="-0.077" /> -->
	<!-- ========================================================================================== -->


	<!-- ========================================================================================== -->
	<!-- <xacro:property name="robot_mechaical_design_offset_x" value="0.015" />
	<xacro:property name="robot_mechaical_design_offset_y" value="0.0231316650320557" />
	<xacro:property name="robot_mechaical_design_offset_z" value="0" /> -->

	<xacro:property name="robot_mechaical_design_offset_x" value="0" />
	<xacro:property name="robot_mechaical_design_offset_y" value="0" />
	<xacro:property name="robot_mechaical_design_offset_z" value="0" />

	<!-- ========================================================================================== -->


	<xacro:property name="camera_mass" value="0.1" />
	<xacro:property name="hokoyu_mass" value="1e-5" />

	<xacro:arg name="frame" default="" />

	<!-- Project center to the ground -->
	<link name="base_footprint">
		<visual>
			<origin xyz="0 0 0.0" rpy="1.57 0 -1.57" />
			<geometry>
				<mesh filename="package://mando_description/meshes/scout_mini/scout_mini_base_link2.dae" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="1.57 0 -1.57" />
			<geometry>
				<mesh filename="package://mando_description/meshes/scout_mini/scout_mini_base_link2.dae" />
				<!-- <box size="0.5 0.5 0.2"/> -->
			</geometry>
		</collision>
	</link>

	<!-- Make Chassis of Bot (Inertia Link) -->
	<link name="chassis">
		<inertial>
			<mass value="50" />
			<origin xyz="0.0 0.0 0.0" />

			<!-- scout mini -->
			<!-- <inertia ixx="1.4476" ixy="0" ixz="0" iyy="0.7715" iyz="0" izz="1.9425" /> -->
			<inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />

			<!-- alpha -->
			<!-- <inertia 
      			ixx="0.147116667" ixy="0" ixz="0"
      			iyy="0.334951167" iyz="0"
      			izz="0.3978345"
      		/> -->

		</inertial>

	</link>

	<!-- Robot base + Inertia  -->
	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0" />
		<parent link="base_footprint" />
		<child link="chassis" />
	</joint>


	<!-- ixx="0.7171" ixy="0.0" ixz="0.0"
				iyy="0.7171" iyz="0.0"
				izz="0.1361" -->

	<!-- Right Wheel Back -->
	<link name="right_wheel_back">
		<inertial>
			<mass value="${robot_wheel_mass}" />
			<origin xyz="0 0 0" rpy="0 1.5707 -1.5707" />
			<!-- <inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" /> -->
			<inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" />

		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 -1.5707" />
			<geometry>
				<!-- <cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/> -->
				<mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" />

			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 -1.5707" />
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}" />
				<!-- <mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" /> -->

			</geometry>
		</collision>

	</link>

	<!-- Right Wheel Front-->
	<link name="right_wheel_front">
		<inertial>
			<mass value="${robot_wheel_mass}" />
			<origin xyz="0 0 0" rpy="0 1.5707 -1.5707" />
			<!-- <inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" /> -->
			<inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 -1.5707" />
			<geometry>
				<!-- <cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/> -->
				<mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 -1.5707" />
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}" />
				<!-- <mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" /> -->
			</geometry>
		</collision>

	</link>


	<!-- Left wheel Back-->
	<link name="left_wheel_back">
		<inertial>
			<mass value="${robot_wheel_mass}" />
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
			<!-- <inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" /> -->
			<inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
			<geometry>
				<!-- <cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/> -->
				<mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}" />
				<!-- <mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" /> -->
			</geometry>
		</collision>

	</link>

	<!-- Left wheel Front-->
	<link name="left_wheel_front">
		<inertial>
			<mass value="${robot_wheel_mass}" />
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
			<!-- <inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" /> -->
			<inertia ixx="0.0107" ixy="0" ixz="0" iyy="0.0107" iyz="0" izz="0.0127" />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
			<geometry>
				<!-- <cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/> -->
				<mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}" />
				<!-- <mesh filename="package://mando_description/meshes/scout_mini/wheel.dae" /> -->
			</geometry>
		</collision>

	</link>

	<!-- Camera -->
	<link name="camera">
		<inertial>
			<mass value="${camera_mass}" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6" />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.05 0.05 0.05" />
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.05 0.05 0.05" />
			</geometry>
		</collision>
	</link>

	<!-- Hokuyo Lidar -->
	<!-- <link name="hokuyo">
		<inertial>
			<mass value="${hokoyu_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>

			<inertia
		        ixx="1e-6" ixy="0.0" ixz="0.0"
		        iyy="1e-6" iyz="0.0"
		        izz="1e-6"
		      />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://mando_gazebo/meshes/hokuyo.dae"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
		</collision>
	</link> -->


	<!-- 2D Lidar  -->
	<link name="base_scan">
		<visual>
			<origin xyz="0 0 0.0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://mando_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001" />
			</geometry>
			<material name="dark" />
		</visual>

		<collision>
			<origin xyz="0.015 0 -0.0065" rpy="0 0 0" />
			<geometry>
				<cylinder length="0.0315" radius="0.055" />
			</geometry>
		</collision>

		<inertial>
			<mass value="0.114" />
			<origin xyz="0 0 0" />
			<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
		</inertial>
	</link>

	<joint name="scan_joint" type="fixed">
		<parent link="chassis" />
		<child link="base_scan" />
		<origin xyz="-0.032 0 0.172" rpy="0 0 0" />
	</joint>


	<!-- IMU Sensor -->
	<joint name="imu_joint" type="fixed">
		<parent link="chassis" />
		<child link="imu_link" />
		<origin xyz="0 0 0" rpy="0 0 0" />
	</joint>

	<link name="imu_link" />


	<!-- 3D Lidar Velodyne  -->
	<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro" />
	<xacro:VLP-16 parent="chassis" name="velodyne" topic="/velodyne_points" hz="10" samples="440">
		<origin xyz="0 0 0.4" rpy="0 0 0" />
	</xacro:VLP-16>


	<!-- Define Joints -->

	<!-- Right Wheel Joint Back-->
	<joint type="continuous" name="right_wheel_hinge_back">
		<!-- <origin xyz="-0.2 -0.30 0" rpy="0 0 0" /> -->
		<origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		<parent link="chassis" />
		<child link="right_wheel_back" />
		<axis xyz="0 1 0" rpy="0 0 0" />
		<!-- <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" /> -->
	</joint>

	<!-- Right Wheel Joint Front-->
	<joint type="continuous" name="right_wheel_hinge_front">
		<!-- <origin xyz="0.2 -0.30 0" rpy="0 0 0" /> -->
		<origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		<parent link="chassis" />
		<child link="right_wheel_front" />
		<axis xyz="0 1 0" rpy="0 0 0" />
		<!-- <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" /> -->
	</joint>


	<!-- Left Wheel Joint Back-->
	<joint type="continuous" name="left_wheel_hinge_back">
		<!-- <origin xyz="-0.2 0.30 0" rpy="0 0 0" /> -->
		<origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		<parent link="chassis" />
		<child link="left_wheel_back" />
		<axis xyz="0 1 0" rpy="0 0 0" />
		<!-- <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" /> -->
	</joint>

	<!-- Left Wheel Joint Front-->
	<joint type="continuous" name="left_wheel_hinge_front">
		<!-- <origin xyz="0.2 0.30 0" rpy="0 0 0" /> -->
		<origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		<parent link="chassis" />
		<child link="left_wheel_front" />
		<axis xyz="0 1 0" rpy="0 0 0" />
		<!-- <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" /> -->
	</joint>

	<!-- Camera Joint -->
	<joint name="camera_joint" type="fixed">
		<origin xyz="0.26 0 0" rpy="0 0 0" />
		<parent link="chassis" />
		<child link="camera" />
		<axis xyz="0 1 0" />
	</joint>

	<!-- Hokoyu Joint -->
	<!-- <joint name="hokuyo_joint" type="fixed">
	    <origin xyz="0.2 0 0.2" rpy="0 0 0" />
	    <parent link="chassis"/>
	    <child link="hokuyo" />  
	    <axis xyz="0 1 0"/> 
	</joint> -->


	<gazebo reference="camera">
		<!-- <material>Gazebo/Red</material> -->
	</gazebo>

	<gazebo reference="chassis">
		<!-- <material>Gazebo/Blue</material> -->
	</gazebo>

	<!-- Color of bot -->
	<gazebo reference="left_wheel_front">
		<!-- <material>Gazebo/Green</material> -->
		<kp>100000000</kp> <!-- kp and kd for rubber -->
		<kd>10.0</kd>
		<mu1>100.0</mu1>
		<mu2>100.0</mu2>
		<maxVel>0.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>

	<gazebo reference="left_wheel_back">
		<!-- <material>Gazebo/Green</material> -->
		<kp>100000000</kp> <!-- kp and kd for rubber -->
		<kd>10.0</kd>
		<mu1>100.0</mu1>
		<mu2>100.0</mu2>
		<maxVel>0.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>

	<gazebo reference="right_wheel_front">
		<!-- <material>Gazebo/Green</material> -->
		<kp>100000000</kp> <!-- kp and kd for rubber -->
		<kd>10.0</kd>
		<mu1>100.0</mu1>
		<mu2>100.0</mu2>
		<maxVel>0.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>
	<gazebo reference="right_wheel_back">
		<!-- <material>Gazebo/Green</material> -->
		<kp>100000000</kp> <!-- kp and kd for rubber -->
		<kd>10.0</kd>
		<mu1>100.0</mu1>
		<mu2>100.0</mu2>
		<maxVel>0.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>


	<!-- Motor, Camera and Lidar Simulation -->
	<xacro:include filename="$(find mando_description)/urdf/scout_mini/scout_mini_ns.gazebo" />

</robot>
